---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Hospital API"
host: "localhost"
basePath: "/"
schemes:
- "https"
produces:
- "application/json"
paths:
  /home:
    get:
      tags:
      - "Main"
      operationId: "homeGET"
      parameters: []
      responses:
        200:
          description: "Main page"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Main"
  /doctors:
    get:
      tags:
      - "Doctors"
      operationId: "doctorsGET"
      parameters: []
      responses:
        200:
          description: "An array of doctors"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Doctor"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Doctors"
  /doctors/{id}}:
    get:
      tags:
      - "Doctors"
      summary: "Specific doctor"
      operationId: "doctorsIdGET"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Doctor object with specific id"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Doctors"
  /me:
    get:
      tags:
      - "User"
      summary: "User page"
      operationId: "meGET"
      parameters: []
      responses:
        200:
          description: "user page"
          schema:
            $ref: "#/definitions/User"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "User"
  /specialty/{id}:
    get:
      tags:
      - "Specialty"
      summary: "Get all doctors of specific specialty"
      operationId: "specialtyIdGET"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "all doctors"
          schema:
            $ref: "#/definitions/Specitalty"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "Specialty"
definitions:
  Role:
    type: "object"
    properties:
      name:
        type: "string"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"
      name:
        type: "string"
      surname:
        type: "string"
      role:
        type: "object"
        properties: {}
      schedule:
        type: "array"
        items:
          $ref: "#/definitions/Schedule"
  Doctor:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Doctor's id"
      name:
        type: "string"
        description: "Doctor's name."
      surname:
        type: "string"
        description: "Doctor's surname."
      specialty:
        type: "string"
        description: "name of doctor's specialty."
      photoUrl:
        type: "string"
        description: "Doctor's photo."
      schedule:
        type: "object"
        properties: {}
  Specitalty:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "Specialty id"
      name:
        type: "string"
        description: "Specialty name"
      doctors:
        type: "array"
        items:
          $ref: "#/definitions/Doctor"
  Schedule:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      room:
        type: "string"
      from_:
        type: "string"
      to_:
        type: "string"
      isFree:
        type: "integer"
        format: "int32"
      doctor:
        type: "object"
        properties: {}
      week:
        type: "object"
        properties: {}
      date:
        type: "string"
        format: "date"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
  Week:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
